### ISSUE TITLE
请问如何确定会评论到哪些微博？

### ISSUE THREAD

**Issue by Nabryant** [mrhuo/WeiboAutoCommentTool#1]
没有看到如何决定会评论到哪些微博？

**Comment by mrhuo** [comment]
你好，现在是直接评论发现页面的所有微博，没有选定评论具体的哪一个

**Comment by Nabryant** [comment]
嗯嗯了解了，感谢回复~






在 2019-01-17 13:37:10，"MrHuo" <notifications@github.com> 写道：


你好，现在是直接评论发现页面的所有微博，没有选定评论具体的哪一个
